version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: expense-tracker-db
    environment:
      POSTGRES_DB: expensetracker
      POSTGRES_USER: srishti
      POSTGRES_PASSWORD: sudan123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: